import { COLORS } from '../../../theme/colors';
/**
 * Milestone Tracking Constants
 */

export const MILESTONE_STATUS = {
  NOT_STARTED: 'not_started',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  ON_HOLD: 'on_hold',
} as const;

export const STATUS_OPTIONS = [
  MILESTONE_STATUS.NOT_STARTED,
  MILESTONE_STATUS.IN_PROGRESS,
  MILESTONE_STATUS.COMPLETED,
  MILESTONE_STATUS.ON_HOLD,
] as const;

export const STATUS_COLORS = {
  [MILESTONE_STATUS.COMPLETED]: COLORS.SUCCESS,
  [MILESTONE_STATUS.IN_PROGRESS]: COLORS.INFO,
  [MILESTONE_STATUS.ON_HOLD]: COLORS.WARNING,
  [MILESTONE_STATUS.NOT_STARTED]: COLORS.DISABLED,
} as const;

export const STATUS_LABELS = {
  [MILESTONE_STATUS.NOT_STARTED]: 'NOT STARTED',
  [MILESTONE_STATUS.IN_PROGRESS]: 'IN PROGRESS',
  [MILESTONE_STATUS.COMPLETED]: 'COMPLETED',
  [MILESTONE_STATUS.ON_HOLD]: 'ON HOLD',
} as const;
