/**
 * Milestone Tracking Constants
 */

export const MILESTONE_STATUS = {
  NOT_STARTED: 'not_started',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  ON_HOLD: 'on_hold',
} as const;

export const STATUS_OPTIONS = [
  MILESTONE_STATUS.NOT_STARTED,
  MILESTONE_STATUS.IN_PROGRESS,
  MILESTONE_STATUS.COMPLETED,
  MILESTONE_STATUS.ON_HOLD,
] as const;

export const STATUS_COLORS = {
  [MILESTONE_STATUS.COMPLETED]: '#4CAF50',
  [MILESTONE_STATUS.IN_PROGRESS]: '#2196F3',
  [MILESTONE_STATUS.ON_HOLD]: '#FF9800',
  [MILESTONE_STATUS.NOT_STARTED]: '#9E9E9E',
} as const;

export const STATUS_LABELS = {
  [MILESTONE_STATUS.NOT_STARTED]: 'NOT STARTED',
  [MILESTONE_STATUS.IN_PROGRESS]: 'IN PROGRESS',
  [MILESTONE_STATUS.COMPLETED]: 'COMPLETED',
  [MILESTONE_STATUS.ON_HOLD]: 'ON HOLD',
} as const;
